language: python
python:
    - 2.7
install:
    - virtualenv --no-site-packages env
    - source env/bin/activate
    - python ./bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
